# Dev config. Compare with the file `kodev create` generates for your Kore version.
bind		127.0.0.1 8888
load		./website.so

skip_chroot	yes
skip_runas	yes

domain * {
	static	/		page
	static	/api/version	api_version
	static	/api/releases	api_releases
}
